export const optionsModel = [
  {
    iconPath:'/assets/mine/m1.png',
    optionName:'我的评价',
    navLink:'/pages/evaluate/index'
  },
  {
    iconPath:'/assets/mine/m2.png',
    optionName:'socket',
    navLink:'/pages/socket/index'
  },
  {
    iconPath:'/assets/mine/m3.png',
    optionName:'暂未开发',
    navLink:''
  },
  {
    iconPath:'/assets/mine/m3.png',
    optionName:'暂未开发',
    navLink:''
  },
  {
    iconPath:'/assets/mine/m3.png',
    optionName:'暂未开发',
    navLink:''
  },
  {
    iconPath:'/assets/mine/m3.png',
    optionName:'暂未开发',
    navLink:''
  }
]